# Database Configuration
database:
  supabase_url: "https://vyfeecfsnvjanhzaojvq.supabase.co"
  supabase_key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5ZmVlY2ZzbnZqYW5oemFvanZxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczNDM0MDExNywiZXhwIjoyMDQ5OTE2MTE3fQ.cBjja9V92dT0-QYmNfIXEgCU00vE91ZXEetTyc-dmBM"

# Cache Configuration
cache:
  directory: ".cache"
  filename: "feed_cache.json"
  duration_minutes: 5

# Feed Processing
feed:
  batch_size: 10
  max_retries: 3
  timeout:
    total: 60
    connect: 10
    read: 30

# Logging
logging:
  directory: "logs"
  level: "INFO"
  max_size_mb: 10
  backup_count: 5

# HTTP Client
http:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  encodings:
    - "utf-8"
    - "iso-8859-1"
    - "iso-8859-2"
    - "windows-1250"
    - "windows-1252" 