# API Keys
mistral_api_key: ${MISTRAL_API_KEY}

# File paths
data_folder: "data"
articles_file: "articles.json"
url_file: "url.md"

# Translation settings
translator:
  source: "auto"
  target: "en"
  delay: 1

# Mistral AI settings
mistral:
  model: "mistral-large-latest"
  prompt_template: |
    Based on this article content, please provide:
    1. A concise title (max 10 words)
    2. A brief summary (max 50 words)
    3. A single category that best describes the article from this exact list only:
    Culture, Economy, Education, Environment, Health, International, Poland, Polish News, 
    Polish Military, Polish Defense, Polish Armed Forces, Polish Air Force, Polish Navy, 
    Polish Army, Polish Security Forces, Polish Intelligence, Polish Foreign Policy, 
    Polish Domestic Policy, Polish Regional News, Polish Economy, Politics, Science, 
    Security, Society, Sports, Technology, Business, Entertainment, Finance, Weather, 
    World News, Crime, Transportation, Travel, History

    Format your response exactly like this:
    TITLE: [your title]
    SUMMARY: [your summary]
    CATEGORY: [select exactly one category from the list above]

    Article content:
    {content}
