# Feed settings
feed:
  entries_to_fetch: 2

# File paths
url_file: "url.md"

# Translation settings
translator:
  source: "auto"
  target: "en"
  delay: 1

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/app.log"

# Ollama settings
ollama:
  model: "phi3.5"
  prompt_template: |
    Based on this article content, please provide:
    1. A concise title (max 20 words)
    2. A long summary (max 100 words)
    3. A single category that best describes the article from this exact list only (you must choose exactly ONE category):
    Culture, Economy, Education, Environment, Health, International, Poland, Polish-News, 
    Polish-Military, Polish-Defense, Polish-Armed-Forces, Polish-Air-Force, Polish-Navy, 
    Polish-Army, Polish-Security-Forces, Polish-Intelligence, Polish-Foreign-Policy, 
    Polish-Domestic-Policy, Polish-Regional-News, Polish-Economy, Politics, Science, 
    Security, Society, Sports, Technology, Business, Entertainment, Finance, Weather, 
    World-News, Crime, Transportation, Travel, History

    CRITICAL RULES FOR CATEGORY SELECTION:
    - You MUST select EXACTLY ONE category - no exceptions!
    - If content fits multiple categories, choose the MOST specific ONE
    - DO NOT use commas or list multiple categories
    - DO NOT add any explanatory text
    - DO NOT create new categories
    - DO NOT combine categories

    Examples:
    CORRECT: CATEGORY: Polish-Military
    WRONG: CATEGORY: Polish-Military, Politics
    WRONG: CATEGORY: Polish-Military and Defense
    WRONG: CATEGORY: Polish-Military (with political aspects)

    Your response MUST follow this EXACT format:
    TITLE: [your title]
    SUMMARY: [your summary]
    CATEGORY: [EXACTLY ONE category from the list - no commas, no explanations]

    Article content:
    {content}
